name: to_do_list_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_slidable: ^3.0.0
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.11
  audioplayers: ^4.0.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#FFF59D"
  image: assets/icon.png
  android: true
  ios: true
flutter:
  uses-material-design: true

  assets:
    - assets/me.jpg
    - assets/social_media_icons/
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
